### ISSUE TITLE
Duplicate entries

### ISSUE THREAD

**Issue by mountainMath** [fcorowe/mappingeuflows#1] opened 2020-07-09 00:29 UTC
Several places in Norway that appear more than once. The following code picks up duplicate rows that only differ by the `flows` column from a previous row in the table. (Excluding flows that are 0, there are some duplicates with those too.)

```
library(dplyr)
readRDS(here::here("data/EU_OD_flows.rds")) %>%
  filter(flows>0) %>%
  filter(duplicated(select(.,-flows))) 
```

For example,
```
readRDS(here::here("data/EU_OD_flows.rds")) %>%
  filter(Origin=="Nes",Destination=="Asker")
```
yields the following

  | Origin | Destination | flows | or_Lon | or_Lat | des_Lon | des_Lat | ISO_code | country_name
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
358616 | Nes | Asker | 1 | 11.498180 | 60.13968 | 10.41741 | 59.83489 | NOR | Norway
366716 | Nes | Asker | 1 | 9.070875 | 60.55212 | 10.41741 | 59.83489 | NOR | Norway
388417 | Nes | Asker | 3 | 9.070875 | 60.55212 | 10.41741 | 59.83489 | NOR | Norway
393017 | Nes | Asker | 3 | 11.498180 | 60.13968 | 10.41741 | 59.83489 | NOR | Norway

with rows 1&4 and 2&3 being identical, except for the flow. How should those be interpreted?

**Comment by patnik** [comment] 2020-07-09 09:03
Thanks a lot for your comment. 
It seemed that the regions you have flagged are split into subregions. 
We have now updated the dataset. 
You will notice that the names have changed slightly as we wanted to make sure we consider only the unique origins/destinations. 

Please let us know if these changes solved all the issues you had.

**Comment by fcorowe** [comment] 2020-07-09 09:16
We are going to close the issue for now -as we think this should resolve the confusion. But please feel free to reopen it if this is not the case. Thanks for your careful look at the data.

**Closed as completed by fcorowe** 2020-07-09 09:16 UTC

**Comment by mountainMath** [comment] 2020-07-09 16:45
Thanks, this clears up all the duplicates for me.

One other question. I am trying to understand the self-flows. It seems to me that for most countries these are internal migrants, but in France and Spain they also include non-migrants?

**Comment by fcorowe** [comment] 2020-07-12 21:10
Right - I had a closer look at the data and I see what is causing confusion. The issue is the diagonal of the origin-destination matrix was included in the dataset (but no mapped). It includes intra-regional moves, but not for all countries so we have decided to remove the diagonal to avoid confusion. 

To answer your question, yes, France and Spain include non-migrants and intra-regional migrants.
